import os
import pytest
import allure
from base.apiutil import RequestBase
from common.readyaml import get_testcase_yaml
from conf.setting import DIR_BASE
from common.recordlog import logs

# 1. 定义自动生成用例所在的目录
auto_gen_dir = os.path.join(DIR_BASE, 'testcase', 'AutoGenerate')

# 2. 动态扫描该目录下所有的 .yaml 文件
yaml_files = []
if os.path.exists(auto_gen_dir):
    for file_name in os.listdir(auto_gen_dir):
        if file_name.endswith('.yaml'):
            yaml_files.append(os.path.join(auto_gen_dir, file_name))
else:
    logs.warning("未找到自动生成的用例目录！")

# 3. 汇总所有 YAML 文件中的测试数据
all_test_data = []
for yml_file in yaml_files:
    cases = get_testcase_yaml(yml_file)
    if cases:
        all_test_data.extend(cases)

# 4. 将汇总的数据喂给 Pytest 执行引擎
@allure.feature('Swagger自动生成接口自动化测试')
class TestAutoGeneratedApi:

    # 只有当 all_test_data 有数据时才执行，避免没生成用例时报错
    @pytest.mark.skipif(not all_test_data, reason="没有找到自动生成的 YAML 用例文件")
    @pytest.mark.parametrize('base_info, testcase', all_test_data)
    def test_auto_api(self, base_info, testcase):
        # 动态给 Allure 报告中的用例打上标题
        allure.dynamic.title(testcase['case_name'])
        # 调用你的核心请求引擎发起测试
        RequestBase().specification_yaml(base_info, testcase)