[api_envi]
host = http://127.0.0.1:8787

[MYSQL]
host = *****
port = 3306
username = root
password = 12345
database = zqsjfx

[REDIS]
host = Redis服务器ip
port = 7005
username = ""
password = ""
db = db0

[CLICKHOUSE]
host = *******
port = 8123
username = default
password =
timeout = 10
db = default

[MongoDB]
host = MongoDB库的ip地址
port = 27017
username = admin
password = 123456
database = admin

[EMAIL]
host = smtp.qq.com
port = 25
user = 3380170838@qq.com
passwd = dosxbvqdlhufdaae
addressee = 3380170838@qq.com
subject = 智慧物流系统-自动化测试报告

[SSH]
host = ******
port = 22
username = root
password = *******
timeout = 10
command = cat /logs/web_app/zjjtsjzf/zjjtsjzf-api/common-default.log

;默认为allure，则生成allure报告，若=tm，则生成tmreport报告
[JENKINS]
url = http://127.0.0.1:8080
username = admin
password = your_jenkins_api_token
timeout = 10
job_name = logistics-api-test

[REPORT_TYPE]
type = allure

[SWAGGER]
# 这里填入你们研发提供的 Swagger/OpenAPI JSON 格式地址
url = https://petstore.swagger.io/v2/swagger.json
# 自动生成的 yaml 用例存放相对目录
output_dir = ./testcase/AutoGenerate
